version: '3'

services:
  postgresql:
    image: postgres:13.2
    container_name: great-escape-api-monolith_postgresql
    # volumes:
    #     - ~/volumes/jhipster/GreatEscapeApiMonolith/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=api-monolith
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    #command: ["postgres", "-c", "log_statement=all"]

  mailcatcher:
    container_name: great-escape-api-monolith_mailcatcher
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080
      - 1025:1025

  wiremock:
    container_name: great-escape-api-monolith_wiremock
    image: rodolpheche/wiremock
    volumes:
      - ./var/wiremock:/home/wiremock
    ports:
      - 8099:80
    command:
      - java
      - -cp
      - /var/wiremock/lib/*:/var/wiremock/extensions/*
      - com.github.tomakehurst.wiremock.standalone.WireMockServerRunner
      - --local-response-templating
      - --port=80
      - --verbose
