services:
  postgresql:
    image: postgres:14.2
    environment:
      POSTGRES_DB: api-monolith
      POSTGRES_USER: api-monolith
      POSTGRES_PASSWORD: api-monolith
    ports:
      - 5432:5432
    command: [ "postgres", "-c", "log_statement=all" ]

  mailcatcher:
    image: sj26/mailcatcher:v0.9.0
    ports:
      - 1080:1080
      - 1025:1025

  wiremock:
    image: wiremock/wiremock:2.32.0
    volumes:
      - ./var/wiremock:/home/wiremock
    ports:
      - 8099:80
    command:
      - java
      - -cp
      - /var/wiremock/lib/*:/var/wiremock/extensions/*
      - com.github.tomakehurst.wiremock.standalone.WireMockServerRunner
      - --local-response-templating
      - --port=80
      - --verbose
