version: '3'

services:
  #  app:
  #    image: great-escape-api-monolith-app
  #    container_name: great-escape-api-monolith_app
  #    environment:
  #      - _JAVA_OPTIONS=-Xmx512m -Xms256m
  #      - SPRING_PROFILES_ACTIVE=prod,swagger
  #      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/api-monolith
  #      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  #    ports:
  #      - 8080:8080

  postgresql:
    image: postgres:12.3
    container_name: great-escape-api-monolith_postgresql
    # volumes:
    #     - ~/volumes/jhipster/GreatEscapeApiMonolith/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=api-monolith
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

  mailcatcher:
    container_name: great-escape-api-monolith_mailcatcher
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080
      - 1025:1025
