spring:
  cloud:
    gcp:
      sql:
        enabled: true
        database-name: 'api-monolith'
        instance-connection-name: 'great-escape-294716:europe-west1:api-monolith'
  datasource:
    username: 'api-monolith'
    password: 'qwerty7890'
    initialization-mode: always
    continue-on-error: true
