version: '2'
services:
  postgresql:
    image: postgres:12.3
    container_name: great-escape-api-monolith_postgresql
    # volumes:
    #     - ~/volumes/jhipster/GreatEscapeApiMonolith/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=api-monolith
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
